# volumeRecovery specifies required actions and their inputs to recover a kubernetes volume
apiVersion: stash.appscode.com/v1alpha2
kind: StashTemplate
metadata:
  name: volumeRecovery
spec:
  actions:
  - name: volumeRecovery
    inputs:
      volumeName: targetVolumeName
      repository: resticRepository
      storageSecret: storageSecret
  - name: stashUpdateRecovery
    inputs:
      recoveryName: recoveryName
