/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/appscode/stash/apis/stash/v1alpha2"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ProcedureLister helps list Procedures.
type ProcedureLister interface {
	// List lists all Procedures in the indexer.
	List(selector labels.Selector) (ret []*v1alpha2.Procedure, err error)
	// Get retrieves the Procedure from the index for a given name.
	Get(name string) (*v1alpha2.Procedure, error)
	ProcedureListerExpansion
}

// procedureLister implements the ProcedureLister interface.
type procedureLister struct {
	indexer cache.Indexer
}

// NewProcedureLister returns a new ProcedureLister.
func NewProcedureLister(indexer cache.Indexer) ProcedureLister {
	return &procedureLister{indexer: indexer}
}

// List lists all Procedures in the indexer.
func (s *procedureLister) List(selector labels.Selector) (ret []*v1alpha2.Procedure, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.Procedure))
	})
	return ret, err
}

// Get retrieves the Procedure from the index for a given name.
func (s *procedureLister) Get(name string) (*v1alpha2.Procedure, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha2.Resource("procedure"), name)
	}
	return obj.(*v1alpha2.Procedure), nil
}
