/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/appscode/stash/apis/stash/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProcedures implements ProcedureInterface
type FakeProcedures struct {
	Fake *FakeStashV1alpha2
}

var proceduresResource = schema.GroupVersionResource{Group: "stash.appscode.com", Version: "v1alpha2", Resource: "procedures"}

var proceduresKind = schema.GroupVersionKind{Group: "stash.appscode.com", Version: "v1alpha2", Kind: "Procedure"}

// Get takes name of the procedure, and returns the corresponding procedure object, and an error if there is any.
func (c *FakeProcedures) Get(name string, options v1.GetOptions) (result *v1alpha2.Procedure, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(proceduresResource, name), &v1alpha2.Procedure{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Procedure), err
}

// List takes label and field selectors, and returns the list of Procedures that match those selectors.
func (c *FakeProcedures) List(opts v1.ListOptions) (result *v1alpha2.ProcedureList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(proceduresResource, proceduresKind, opts), &v1alpha2.ProcedureList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.ProcedureList{ListMeta: obj.(*v1alpha2.ProcedureList).ListMeta}
	for _, item := range obj.(*v1alpha2.ProcedureList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested procedures.
func (c *FakeProcedures) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(proceduresResource, opts))
}

// Create takes the representation of a procedure and creates it.  Returns the server's representation of the procedure, and an error, if there is any.
func (c *FakeProcedures) Create(procedure *v1alpha2.Procedure) (result *v1alpha2.Procedure, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(proceduresResource, procedure), &v1alpha2.Procedure{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Procedure), err
}

// Update takes the representation of a procedure and updates it. Returns the server's representation of the procedure, and an error, if there is any.
func (c *FakeProcedures) Update(procedure *v1alpha2.Procedure) (result *v1alpha2.Procedure, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(proceduresResource, procedure), &v1alpha2.Procedure{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Procedure), err
}

// Delete takes name of the procedure and deletes it. Returns an error if one occurs.
func (c *FakeProcedures) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(proceduresResource, name), &v1alpha2.Procedure{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProcedures) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(proceduresResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.ProcedureList{})
	return err
}

// Patch applies the patch and returns the patched procedure.
func (c *FakeProcedures) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.Procedure, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(proceduresResource, name, data, subresources...), &v1alpha2.Procedure{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Procedure), err
}
