/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/appscode/stash/apis/stash/v1beta1"
	scheme "github.com/appscode/stash/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RecoveryConfigurationsGetter has a method to return a RecoveryConfigurationInterface.
// A group's client should implement this interface.
type RecoveryConfigurationsGetter interface {
	RecoveryConfigurations(namespace string) RecoveryConfigurationInterface
}

// RecoveryConfigurationInterface has methods to work with RecoveryConfiguration resources.
type RecoveryConfigurationInterface interface {
	Create(*v1beta1.RecoveryConfiguration) (*v1beta1.RecoveryConfiguration, error)
	Update(*v1beta1.RecoveryConfiguration) (*v1beta1.RecoveryConfiguration, error)
	UpdateStatus(*v1beta1.RecoveryConfiguration) (*v1beta1.RecoveryConfiguration, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.RecoveryConfiguration, error)
	List(opts v1.ListOptions) (*v1beta1.RecoveryConfigurationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.RecoveryConfiguration, err error)
	RecoveryConfigurationExpansion
}

// recoveryConfigurations implements RecoveryConfigurationInterface
type recoveryConfigurations struct {
	client rest.Interface
	ns     string
}

// newRecoveryConfigurations returns a RecoveryConfigurations
func newRecoveryConfigurations(c *StashV1beta1Client, namespace string) *recoveryConfigurations {
	return &recoveryConfigurations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the recoveryConfiguration, and returns the corresponding recoveryConfiguration object, and an error if there is any.
func (c *recoveryConfigurations) Get(name string, options v1.GetOptions) (result *v1beta1.RecoveryConfiguration, err error) {
	result = &v1beta1.RecoveryConfiguration{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("recoveryconfigurations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RecoveryConfigurations that match those selectors.
func (c *recoveryConfigurations) List(opts v1.ListOptions) (result *v1beta1.RecoveryConfigurationList, err error) {
	result = &v1beta1.RecoveryConfigurationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("recoveryconfigurations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested recoveryConfigurations.
func (c *recoveryConfigurations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("recoveryconfigurations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a recoveryConfiguration and creates it.  Returns the server's representation of the recoveryConfiguration, and an error, if there is any.
func (c *recoveryConfigurations) Create(recoveryConfiguration *v1beta1.RecoveryConfiguration) (result *v1beta1.RecoveryConfiguration, err error) {
	result = &v1beta1.RecoveryConfiguration{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("recoveryconfigurations").
		Body(recoveryConfiguration).
		Do().
		Into(result)
	return
}

// Update takes the representation of a recoveryConfiguration and updates it. Returns the server's representation of the recoveryConfiguration, and an error, if there is any.
func (c *recoveryConfigurations) Update(recoveryConfiguration *v1beta1.RecoveryConfiguration) (result *v1beta1.RecoveryConfiguration, err error) {
	result = &v1beta1.RecoveryConfiguration{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("recoveryconfigurations").
		Name(recoveryConfiguration.Name).
		Body(recoveryConfiguration).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *recoveryConfigurations) UpdateStatus(recoveryConfiguration *v1beta1.RecoveryConfiguration) (result *v1beta1.RecoveryConfiguration, err error) {
	result = &v1beta1.RecoveryConfiguration{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("recoveryconfigurations").
		Name(recoveryConfiguration.Name).
		SubResource("status").
		Body(recoveryConfiguration).
		Do().
		Into(result)
	return
}

// Delete takes name of the recoveryConfiguration and deletes it. Returns an error if one occurs.
func (c *recoveryConfigurations) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("recoveryconfigurations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *recoveryConfigurations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("recoveryconfigurations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched recoveryConfiguration.
func (c *recoveryConfigurations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.RecoveryConfiguration, err error) {
	result = &v1beta1.RecoveryConfiguration{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("recoveryconfigurations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
