apiVersion: stash.appscode.com/v1alpha2
kind: BackupConfiguration
metadata:
  name: backup-volume-demo
  namespace: demo
spec:
  schedule: '@every 1h'
  # stashTemplate indicates StashTemplate crd to use for backup the target volume.
  # stash will create some default StashTemplate  while install to backup/recover various resources.
  # user can also crate their own StashTemplate to customize backup/recovery
  stashTemplate: volumeBackup
  # repository refers to the Repository crd that hold backend information
  repository:
    name: stash-backup-repo
  # target indicate the target workload that we want to backup
  target:
    volume:
      mountPath: /source/data
      persistentVolumeClaim:
        claimName: stash-recovered
  # retentionPolicies specify the policy to follow to clean old backup snapshots
  retentionPolicy:
    keepLast: 5
    prune: true
  # containerAttributes is an optional field that can be use to set some attributes 
  # like resources, securityContext etc. to backup sidecar container
  containerAttributes:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
