apiVersion: stash.appscode.com/v1alpha1
kind: Backup
metadata:
  name: backup-database-demo
  namespace: default
spec:
  backupType: Scheduled
  schedule: '@every 1h'
  backupAgent: PgBackup
  repository:
    name: stash-backup-repo
    namespace: demo
  backupTarget:
    targetType: Database
    # appRef inidcates the AppBinding crd that holds connection information of respective database
    # for databases deployed with KubeDB, AppBinding will be created automatically.
    # for databases deployed without KubeDB, you have to create it manually
    appRef:
      name: quick-postgres
      namespace: demo
    databases:
      - postgres
      - mypgdb
    retentionPolicyName: 'keep-last-5'
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true
  containerAttributes:
    annotations:
      iam.amazonaws.com/role: MyIAMRole
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
