apiVersion: stash.appscode.com/v1alpha2
kind: Backup
metadata:
  name: backup-volume-demo
  namespace: demo
spec:
  schedule: '@every 1h'
  # backupAgent indicates AgentTemplate crd to use for backup the target volume.
  # stash will create some default AgentTemplate  while install to backup/recover various resources.
  # user can also crate their own AgentTemplate to customize backup/recovery
  backupAgent:
    name: stashVolumeBackup
  # repository refers to the Repository crd that hold backend information
  repository:
    name: stash-backup-repo
  # targetRef indicate the target workload that we want to backup
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stash-demo
  # targetDirectories indicates the directories inside the workload we want to backup
  targetDirectories:
  - /source/data
# retentionPolicies specify the policy to follow to clean old backup snapshots
  retentionPolicy:
    keepLast: 5
    prune: true
  # containerAttributes is an optional field that can be use to set some attributes 
  # like resources, securityContext etc. to backup sidecar container
  containerAttributes:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
