/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/appscode/stash/apis/stash/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRecoveryConfigurations implements RecoveryConfigurationInterface
type FakeRecoveryConfigurations struct {
	Fake *FakeStashV1beta1
	ns   string
}

var recoveryconfigurationsResource = schema.GroupVersionResource{Group: "stash.appscode.com", Version: "v1beta1", Resource: "recoveryconfigurations"}

var recoveryconfigurationsKind = schema.GroupVersionKind{Group: "stash.appscode.com", Version: "v1beta1", Kind: "RecoveryConfiguration"}

// Get takes name of the recoveryConfiguration, and returns the corresponding recoveryConfiguration object, and an error if there is any.
func (c *FakeRecoveryConfigurations) Get(name string, options v1.GetOptions) (result *v1beta1.RecoveryConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(recoveryconfigurationsResource, c.ns, name), &v1beta1.RecoveryConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.RecoveryConfiguration), err
}

// List takes label and field selectors, and returns the list of RecoveryConfigurations that match those selectors.
func (c *FakeRecoveryConfigurations) List(opts v1.ListOptions) (result *v1beta1.RecoveryConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(recoveryconfigurationsResource, recoveryconfigurationsKind, c.ns, opts), &v1beta1.RecoveryConfigurationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.RecoveryConfigurationList{ListMeta: obj.(*v1beta1.RecoveryConfigurationList).ListMeta}
	for _, item := range obj.(*v1beta1.RecoveryConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested recoveryConfigurations.
func (c *FakeRecoveryConfigurations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(recoveryconfigurationsResource, c.ns, opts))

}

// Create takes the representation of a recoveryConfiguration and creates it.  Returns the server's representation of the recoveryConfiguration, and an error, if there is any.
func (c *FakeRecoveryConfigurations) Create(recoveryConfiguration *v1beta1.RecoveryConfiguration) (result *v1beta1.RecoveryConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(recoveryconfigurationsResource, c.ns, recoveryConfiguration), &v1beta1.RecoveryConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.RecoveryConfiguration), err
}

// Update takes the representation of a recoveryConfiguration and updates it. Returns the server's representation of the recoveryConfiguration, and an error, if there is any.
func (c *FakeRecoveryConfigurations) Update(recoveryConfiguration *v1beta1.RecoveryConfiguration) (result *v1beta1.RecoveryConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(recoveryconfigurationsResource, c.ns, recoveryConfiguration), &v1beta1.RecoveryConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.RecoveryConfiguration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRecoveryConfigurations) UpdateStatus(recoveryConfiguration *v1beta1.RecoveryConfiguration) (*v1beta1.RecoveryConfiguration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(recoveryconfigurationsResource, "status", c.ns, recoveryConfiguration), &v1beta1.RecoveryConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.RecoveryConfiguration), err
}

// Delete takes name of the recoveryConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeRecoveryConfigurations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(recoveryconfigurationsResource, c.ns, name), &v1beta1.RecoveryConfiguration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRecoveryConfigurations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(recoveryconfigurationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.RecoveryConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched recoveryConfiguration.
func (c *FakeRecoveryConfigurations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.RecoveryConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(recoveryconfigurationsResource, c.ns, name, data, subresources...), &v1beta1.RecoveryConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.RecoveryConfiguration), err
}
