/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/appscode/stash/apis/stash/v1alpha2"
	scheme "github.com/appscode/stash/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ProceduresGetter has a method to return a ProcedureInterface.
// A group's client should implement this interface.
type ProceduresGetter interface {
	Procedures() ProcedureInterface
}

// ProcedureInterface has methods to work with Procedure resources.
type ProcedureInterface interface {
	Create(*v1alpha2.Procedure) (*v1alpha2.Procedure, error)
	Update(*v1alpha2.Procedure) (*v1alpha2.Procedure, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha2.Procedure, error)
	List(opts v1.ListOptions) (*v1alpha2.ProcedureList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.Procedure, err error)
	ProcedureExpansion
}

// procedures implements ProcedureInterface
type procedures struct {
	client rest.Interface
}

// newProcedures returns a Procedures
func newProcedures(c *StashV1alpha2Client) *procedures {
	return &procedures{
		client: c.RESTClient(),
	}
}

// Get takes name of the procedure, and returns the corresponding procedure object, and an error if there is any.
func (c *procedures) Get(name string, options v1.GetOptions) (result *v1alpha2.Procedure, err error) {
	result = &v1alpha2.Procedure{}
	err = c.client.Get().
		Resource("procedures").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Procedures that match those selectors.
func (c *procedures) List(opts v1.ListOptions) (result *v1alpha2.ProcedureList, err error) {
	result = &v1alpha2.ProcedureList{}
	err = c.client.Get().
		Resource("procedures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested procedures.
func (c *procedures) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("procedures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a procedure and creates it.  Returns the server's representation of the procedure, and an error, if there is any.
func (c *procedures) Create(procedure *v1alpha2.Procedure) (result *v1alpha2.Procedure, err error) {
	result = &v1alpha2.Procedure{}
	err = c.client.Post().
		Resource("procedures").
		Body(procedure).
		Do().
		Into(result)
	return
}

// Update takes the representation of a procedure and updates it. Returns the server's representation of the procedure, and an error, if there is any.
func (c *procedures) Update(procedure *v1alpha2.Procedure) (result *v1alpha2.Procedure, err error) {
	result = &v1alpha2.Procedure{}
	err = c.client.Put().
		Resource("procedures").
		Name(procedure.Name).
		Body(procedure).
		Do().
		Into(result)
	return
}

// Delete takes name of the procedure and deletes it. Returns an error if one occurs.
func (c *procedures) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("procedures").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *procedures) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("procedures").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched procedure.
func (c *procedures) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.Procedure, err error) {
	result = &v1alpha2.Procedure{}
	err = c.client.Patch(pt).
		Resource("procedures").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
