apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  namespace: demo
  # if stash find bellow annotations, it will take backup of it.
  annotations:
    stash.appscode.com/defaultbackupconfiguration: "volume-default-backup-configuration"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
