apiVersion: stash.appscode.com/v1alpha2
kind: Recovery
metadata:
  name: recovery-database-demo
  namespace: demo
spec:
  repository:
    name: stash-backup-repo
    namespace: demo
  paths:
  - /source/data
  recoverTo:
    # indicates the running workload where we want to recover
    workload:
      apiVersion: apps/v1
      kind: Deployment
      name: stash-demo
  # recoveryPolicy specifies weather to recover only once or recover always when workload restart for a particular Recovery crd.
  # It can be either "IfNotRecovered" or "Always"
  # If "Always" is used, whenever the target workload restart, it will recover first.
  recoveryPolicy: Always
