apiVersion: stash.appscode.com/v1alpha2
kind: Recovery
metadata:
  name: recovery-volume-demo
  namespace: demo
spec:
  repository:
    name: stash-backup-repo
    namespace: demo
  # stashTemplate indicates StashTemplate crd to use for creating recovery job
  stashTemplate: volumeRecovery
  # paths specifies the directories to recover from the backed up data
  paths:
  - /source/data
  recoverTo:
    # indicates the volume where the recovered data will be stored
    volume:
      mountPath: /source/data
      persistentVolumeClaim:
        claimName: stash-recovered
