# =========== Repository CRD(created by user) ====================
apiVersion: stash.appscode.com/v1alpha2
kind: Repository
metadata:
  name: stash-backup-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: stash-backup-repo
      prefix: default/deployment/stash-demo
    storageSecretName: gcs-secret
---

# =========== BackupConfiguration CRD ( created by user)=============
apiVersion: stash.appscode.com/v1alpha2
kind: BackupConfiguration
metadata:
  name: backup-database-demo
  namespace: demo
spec:
  schedule: '@every 1h'
  backupTemplate:
    name: pgBackup
  repository:
    name: stash-backup-repo
  targetRef:
    apiVersion: appcatalog.appscode.com/v1alpha1
    kind: AppBinding
    name: quick-postgres
  retentionPolicy:
    keepLast: 5
    prune: true
  containerAttributes:
    args:
    - mydb
    - anotherdb
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  podAttributes:
    nodeSelector:
      cloud.google.com/gke-nodepool: pool-highcpu32
    serviceAccountName: stash-demo
---

# ============= BackupInstance CRD (created by stash operator) ===============
apiVersion: stash.appscode.com/v1alpha2
kind: BackupInstance
metadata:
  name: backup-database-demo-instance
  namespace: demo
spec:
  targetBackupConfiguration: backup-volume-demo
---

# =========== BackupTemplate CRD (created while stash install) ==============
apiVersion: stash.appscode.com/v1alpha2
kind: BackupTemplate
metadata:
  name: pgBackup
spec:
  actions:
  - name: stashInit
    inputs:
      repoName: repositoryName # operator will provide these value
      resticSecret: resticSecret
  - name: pgBackup
    inputs:
      databases: databases
      databaseSecret: databaseSecret
      host: hostURL
      repository: resticRepository
      resticSecret: resticSecret
  - name: stashUpdateRepo
    inputs:
      repoName: repoName
      resticSecret: resticSecret
---

# ========== Action (created automatically while install stash) ========================
apiVersion: stash.appscode.com/v1alpha2
kind: Action
metadata:
  name: stashInit
spec:
  container:
    image: appscode/stash:0.9.0
    name:  stash-init
    command: ["init"]
    args:
    - repository=$(repoName)
    envFrom:
    - secretRef:
        name: $(resticSecret)
---

apiVersion: stash.appscode.com/v1alpha2
kind: Action
metadata:
  name: pgBackup
spec:
   container:
      image: kubedb/postgres-tools:0.9.0
      name:  postgres-tools
      command: ["backup"]
      args: [$(databases)]
      env:
      - name:  PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: $(databaseSecret)
            key: "POSTGRES_PASSWORD"
      - name:  DB_USER
        valueFrom:
          secretKeyRef:
            name: $(databaseSecret)
            key: "POSTGRES_USER"
      - name:  DB_HOST
        value: $(host)
      - name: DATA_DIR
        value: $(dataDir=/tmp/backup)
      - name: RESTIC_REPOSITORY
        value: $(repository)
      envFrom:
      - secretRef:
          name: $(resticSecret)
---

apiVersion: stash.appscode.com/v1alpha2
kind: Action
metadata:
  name: stashUpdateRepo
spec:
  container:
    image: appscode/stash:0.9.0
    name:  stash-repo-update
    command: ["update-repo"]
    args:
    - repository=$(repoName)
    envFrom:
    - secretRef:
        name: $(resticSecret)
