apiVersion: stash.appscode.com/v1alpha2
kind: AgentTemplate
metadata:
  name: pgBackup
spec:
  initContainers:
  # stash-init initialize repository if it does not exist in the backend
  - image: appscode/stash:0.8.2
    name: stash-init
    args:
    - init
    - --backup-name=$(BACKUP_NAME)
  # postgres-tools take backup of the database
  - image: kubedb/postgres-tools:0.9.0
    name:  postgres-tools
    command: ["backup"]
    env:
    - name:  PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: <secret name>
          key: "POSTGRES_PASSWORD"
    - name:  DB_USER
      valueFrom:
        secretKeyRef:
          name: <secret name>
          key: "POSTGRES_USER"
    - name:  DB_HOST
      value: <host url>
    - name: DATA_DIR
      value: <data-dir>
  containers:
  # stash-update-status update Repository crd status and push backup metrics to pushgateway
  - image: appscode/stash:0.8.2
    name:  stash-update-status
    args:
    - update-repo-status
    - --backup-name=$(BACKUP_NAME)
    - --pushgateway-url=$(PUSH_GATEWAY_URL)
    - --enable-status-subresource=$(ENABLE_STATUS_SUB_RESOURCE)
    - --metrics-dir=/tmp/metrics.txt
